<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net4.8</TargetFramework>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <Optimize>False</Optimize>
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Northwood.LabAPI" Version="1.1.6.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\..\..\dependancies\Dev\Assembly-CSharp-firstpass.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\dependancies\Dev\Assembly-CSharp-Publicized.dll</HintPath>
    </Reference>
    <Reference Include="Mirror">
      <HintPath>..\..\..\dependancies\Dev\Mirror.dll</HintPath>
    </Reference>
    <Reference Include="Pooling">
      <HintPath>..\..\..\dependancies\Dev\Pooling.dll</HintPath>
    </Reference>
    <Reference Include="ProjectMER">
      <HintPath>..\..\..\dependancies\plugins\ProjectMER.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine">
      <HintPath>..\..\..\dependancies\Dev\UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\dependancies\Dev\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.PhysicsModule">
      <HintPath>..\..\..\dependancies\Dev\UnityEngine.PhysicsModule.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
